### ISSUE TITLE
Failure in getFeedSubmissionResult

### ISSUE THREAD

**Issue by moltar** [MJBlack23/mws-sdk#2]
```js
const api = new Feeds()

api
  .getFeedSubmissionResult('51774018291')
  .then((res) => console.log(res))
```

```
(node:8248) UnhandledPromiseRejectionWarning: Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: F
    at error (~prj/node_modules/sax/lib/sax.js:651:10)
    at strictFail (~prj/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (~prj/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (~prj/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (~prj/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (~prj/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (~prj/node_modules/xml2js/lib/parser.js:369:19)
    at Promise (internal/util.js:275:30)
    at new Promise (<anonymous>)
    at internal/util.js:274:12
(node:8248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas?

Thanks for the module, btw!

**Comment by MJBlack23** [comment]
What happens if you catch and log the error?

```
const api = new Feeds()
api
  .getFeedSubmissionResult('51774018291')
  .then((res) => console.log(res))
  .catch(error => console.log(error))
```
